name: release

on:
  push:
    branches:
    - "release/*"

env:
  BASE_NAME: NDummy
  EXE_NAME: ndummy
  PROJECT_PATH: src/NDummy/NDummy.csproj
  CONFIGURATION: Release
  DOTNET_VERSION: 8

jobs:
  release:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - platform: windows-latest
            runtime: win-x64
            exe: ${{ env.EXE_NAME }}.exe
          - platform: macos-latest
            runtime: osx-x64
            exe: ${{ env.EXE_NAME }}
          - platform: ubuntu-latest
            runtime: linux-x64
            exe: ${{ env.EXE_NAME }}

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Set version
      id: environments
      run: |
        branch_name=${{ github.ref_name }}
        split=(${branch_name//// })
        version=${split[1]}
        echo "Version: $version"
        echo "version=${version}" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore /p:Version=${{ steps.environments.outputs.version }}

    - name: Publish
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --runtime ${{ matrix.runtime }} --output ./artifacts/ /p:Version=${{ steps.environments.outputs.version }}

    - name: Archive
      run: |
        zip -j ${{ env.BASE_NAME }}-${{ matrix.runtime }}.zip ./artifacts/${{ matrix.exe }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Ver.${{ steps.environments.outputs.version }}
        tag_name: v${{ steps.environments.outputs.version }}
        files: |
          ${{ env.BASE_NAME }}-${{ matrix.runtime }}.zip
